<?php
/* @var Phwoolcon\View\Engine\Php $this */
?>
<h3><?= __('This page is just a demonstration, please do NOT make any real payments') ?></h3>
<ul class="non-list">
    <li>
        <div class="details">
            <h1>Test product</h1>
            <h2><?= price(0.01) ?></h2>
        </div>
        <div>
            <a href="<?= url('pay/form') ?>"><?= __('Buy') ?></a>
        </div>
    </li>
</ul>
