<?php
/* @var Phwoolcon\View\Engine\Php $this */
?>
<h1><?= __('Demo Request Form') ?></h1>
<p>This is a payment request form for demonstration purpose only.</p>
<form method="post" action="<?= url('api/alipay/pay-request', null, true) ?>" enctype="application/x-www-form-urlencoded">
    <ul class="non-list">
        <li>
            <label>
                <span class="label">trade_id</span>
                <input type="text" name="trade_id" value="<?= Session::getFormData('trade_id') ?>">
                <span>Trade ID is the order ID provided by CP (Content Provider)</span>
            </label>
        </li>
        <li>
            <label>
                <span class="label">amount</span>
                <input type="text" name="amount" value="<?= Session::getFormData('amount') ?>">
                <span>The order grand total amount, float number.</span>
            </label>
        </li>
        <li>
            <label>
                <span class="label">currency</span>
                <input type="hidden" name="currency" value="CNY">
                <input type="text" name="currency" value="CNY" disabled>
            </label>
        </li>
        <li>
            <label>
                <span class="label">product_name</span>
                <input type="text" name="product_name" value="<?= Session::getFormData('product_name') ?>">
            </label>
        </li>
        <li>
            <label>
                <span class="label">client_id</span>
                <input type="hidden" name="client_id" value="test_client">
                <input type="text" name="client_id" value="test_client" disabled>
            </label>
        </li>
        <li>
            <label>
                <span class="label">user_identifier</span>
                <input type="text" name="user_identifier" value="<?= Session::getFormData('user_identifier') ?>">
                <span>A string to identify user.</span>
            </label>
        </li>
        <li>
            <label>
                <span class="label">return_url</span>
                <input type="text" name="return_url" value="<?= Session::getFormData('return_url') ?>">
                <span>Redirect the user back to this URL when payment finished.</span>
            </label>
        </li>
        <li>
            <label>
                <span class="label">callback_url</span>
                <input type="text" name="callback_url" value="<?= Session::getFormData('callback_url') ?>">
                <span>Server will send callback data to this URL if order completed or failed.</span>
            </label>
        </li>
        <li>
            <label>
                <span class="label">sign</span>
                <input type="text" name="sign" value="<?= Session::getFormData('sign') ?>">
                <span>API invocation security.</span>
            </label>
        </li>
    </ul>
    <h3><?= __('Select payment method'); ?></h3>
    <?php foreach (View::getParam('gateways', []) as $gatewayName => $gateway) { ?>
        <?php foreach (fnGet($gateway, 'methods', []) as $methodName => $method) { ?>
            <div class="payment-method payment-method-<?= $gatewayName ?>-<?= $methodName ?>">
                <label>
                    <input type="radio" name="payment_method" value="<?= $paymentMethod = $gatewayName . '.' . $methodName ?>">
                    <span><?= $paymentMethod ?></span>
                    [
                    <span class="gateway-label"><?= __(fnGet($gateway, 'label')) ?></span>
                    <span class="separator">-</span>
                    <span class="method-label"><?= __(fnGet($method, 'label')) ?></span>
                    ]
                </label>
            </div>
        <?php } ?>
    <?php } ?>
    <div>
        <button type="submit"><?= __('Place Order') ?></button>
    </div>
</form>
