<?php
/* @var Phwoolcon\View\Engine\Php $this */
$userData = View::getParam('user_data');
?>
<form id="auth-confirm-form" method="get" target="_self" action="<?= url('account/activate'); ?>" accept-charset="UTF-8">
    <ul class="non-list">
        <li>
            <label><?= fnGet($userData, 'login')?></label>
        </li>
        <li>
            <label><input type="text" name="auth[confirm]" placeholder="<?= __('Confirmation Code'); ?>" autocomplete="off"></label>
        </li>
        <li>
            <button type="submit" class="submit"><span><?= __('Submit'); ?></span></button>
        </li>
        <li>
            <a href="<?= url('account/login'); ?>" class="register"><?= __('Login'); ?></a>
            <a href="<?= url('account/register'); ?>" class="register"><?= __('Register'); ?></a>
        </li>
    </ul>
    <div class="hidden">
        <input type="hidden" name="uid" value="<?= fnGet($userData, 'id'); ?>" autocomplete="off">
    </div>
</form>
