<?php
/* @var Phwoolcon\View\Engine\Php $this */
$userData = View::getParam('user_data');
?>
<form id="auth-confirm-form" method="get" target="_self" action="<?php echo url('account/activate'); ?>" accept-charset="UTF-8">
    <ul class="non-list">
        <li>
            <label><?php echo fnGet($userData, 'login')?></label>
        </li>
        <li>
            <label><input type="text" name="auth[confirm]" placeholder="<?php echo __('Confirmation Code'); ?>"></label>
        </li>
        <li>
            <button type="submit" class="submit"><span><?php echo __('Submit'); ?></span></button>
        </li>
        <li>
            <a href="<?php echo url('account/login'); ?>" class="register"><?php echo __('Login'); ?></a>
            <a href="<?php echo url('account/register'); ?>" class="register"><?php echo __('Register'); ?></a>
        </li>
    </ul>
    <div class="hidden">
        <input type="hidden" name="uid" value="<?php echo fnGet($userData, 'id'); ?>" autocomplete="off">
    </div>
</form>
