<?php
/* @var Phwoolcon\View\Engine\Php $this */
?>
<form id="auth-forgot-password-form" method="post" target="_self" action="<?php echo url('account/forgot-password'); ?>" accept-charset="UTF-8">
    <ul>
        <li>
            <label><input type="text" name="auth[login]" placeholder="<?php echo __('Username, email or mobile'); ?>"></label>
        </li>
        <li>
            <button type="submit" class="submit"><span><?php echo __('Submit'); ?></span></button>
        </li>
        <li>
            <a href="<?php echo url('account/login'); ?>" class="register"><?php echo __('Login'); ?></a>
            <a href="<?php echo url('account/register'); ?>" class="register"><?php echo __('Register'); ?></a>
        </li>
    </ul>
    <div class="hidden">
        <input type="hidden" name="_token" value="<?php echo Session::getCsrfToken(true); ?>" autocomplete="off">
    </div>
</form>
