<?php
/* @var Phwoolcon\View\Engine\Php $this */
?>
<form id="auth-forgot-password-form" method="post" target="_self" action="<?= url('account/forgot-password'); ?>" accept-charset="UTF-8">
    <ul class="non-list">
        <li>
            <label><input type="text" name="auth[login]" placeholder="<?= __('Username, email or mobile'); ?>"></label>
        </li>
        <li>
            <button type="submit" class="submit"><span><?= __('Submit'); ?></span></button>
        </li>
        <li>
            <a href="<?= url('account/login'); ?>" class="register"><?= __('Login'); ?></a>
            <a href="<?= url('account/register'); ?>" class="register"><?= __('Register'); ?></a>
        </li>
    </ul>
    <div class="hidden">
        <input type="hidden" name="_token" value="<?= Session::getCsrfToken(true); ?>" autocomplete="off">
    </div>
</form>
