<?php
/* @var Phwoolcon\View\Engine\Php $this */
?>
<?php if ($user = Auth::getUser()) { ?>
    <div>
        <ul class="non-list">
            <li>
                <label><?= __('ID'); ?></label>
                <span><?= $user->getId(); ?></span>
            </li>
            <li>
                <label><?= __('Username'); ?></label>
                <span><?= $user->getData('username') ?: __('Not set'); ?></span>
            </li>
            <li>
                <label><?= __('Email'); ?></label>
                <span><?= $user->getData('email') ?: __('Not set'); ?></span>
            </li>
            <li>
                <label><?= __('Mobile'); ?></label>
                <span><?= $user->getData('mobile') ?: __('Not set'); ?></span>
            </li>
        </ul>
    </div>
<?php } ?>
