<?php
/* @var Phwoolcon\View\Engine\Php $this */
?>
<form id="auth-login-form" method="post" target="_self" action="<?= url('account/login'); ?>" accept-charset="UTF-8">
    <ul class="non-list">
        <li>
            <label><input type="text" name="auth[login]" value="<?= Session::getFormData('auth_retry.login'); ?>" placeholder="<?= __('Username, email or mobile'); ?>"></label>
        </li>
        <li>
            <label><input type="password" name="auth[password]" placeholder="<?= __('Password'); ?>"></label>
        </li>
        <li>
            <button type="submit" class="submit btn btn-d smooth btn-sm"><span><?= __('Login'); ?></span></button>
        </li>
        <li>
            <label><input type="checkbox" name="auth[remember]" <?php if (Session::getFormData('auth_retry.remember')) { ?>checked="checked"<?php } ?> value="1"><?= __('Remember Login'); ?></label>
            <a href="<?= url('account/forgot-password'); ?>" class="account/forgot-password"><?= __('Forgot password?'); ?></a>
        </li>
        <li>
            <a href="<?= url('account/register'); ?>" class="register"><?= __('Register'); ?></a>
        </li>
    </ul>
    <div class="hidden">
        <input type="hidden" name="_token" value="<?= Session::getCsrfToken(true); ?>" autocomplete="off">
    </div>
</form>
