<?php
/* @var Phwoolcon\View\Engine\Php $this */
?>
<?php
$config = View::getParam('config');
?>
<h1><?= __('Redirecting...'); ?></h1>
<?= View::assets('sso-js'); ?>
<script>
    (function (w, config) {
        $p.sso.setUid(config.uid, config.uidTtl);
        setTimeout(function () {
            w.location.href = config.url;
        }, config.timeout);
    })(window, <?= json_encode($config); ?>);
</script>
<noscript>
    <meta http-equiv="refresh" content="<?= $config['timeout'] / 1000; ?>;URL=<?= $config['url']; ?>">
</noscript>
