<?php
/* @var Phwoolcon\View\Engine\Php $this */
?>
<form id="auth-register-form" method="post" target="_self" action="<?= url('account/register'); ?>" accept-charset="UTF-8">
    <ul class="non-list">
        <li>
            <label><input type="text" name="register[login]" value="<?= Session::getFormData('register_retry.login'); ?>" placeholder="<?= __('Email or mobile'); ?>"></label>
        </li>
        <li>
            <label><input type="password" name="register[password]" placeholder="<?= __('Password'); ?>"></label>
        </li>
        <li>
            <label><input type="password" name="register[confirm_password]" placeholder="<?= __('Confirm password'); ?>"></label>
        </li>
        <li>
            <button type="submit" class="submit btn btn-d smooth btn-sm"><span><?= __('Register'); ?></span></button>
        </li>
        <li>
            <label><input type="checkbox" name="terms" <?php if (Session::getFormData('register_retry.terms')) { ?>checked="checked"<?php } ?> value="1"><?= __('I have read and agree to the [url]Terms of Service[/url]', ['url' => url('terms')]); ?></label>
        </li>
        <li>
            <a href="<?= url('account/login'); ?>" class="login"><?= __('Already registered? Click here to login'); ?></a>
        </li>
    </ul>
    <div class="hidden">
        <input type="hidden" name="_token" value="<?= Session::getCsrfToken(true); ?>" autocomplete="off">
    </div>
</form>
