<?php
/* @var Phwoolcon\View\Engine\Php $this */
$quote = View::getParam('quote');
?>
<h3><?= __('This page is just a demonstration, please do NOT make any real payments') ?></h3>
<h1><?= fnGet($quote, 'brief_description') ?></h1>
<h2><?= price(fnGet($quote, 'amount')) ?></h2>
<h3><?= __('Select payment method'); ?></h3>
<form method="post" action="<?= url('pay/order/place', null, true) ?>" enctype="application/x-www-form-urlencoded">
    <?php foreach (View::getParam('gateways', []) as $gatewayName => $gateway) { ?>
        <?php foreach (fnGet($gateway, 'methods', []) as $methodName => $method) { ?>
            <div class="payment-method payment-method-<?= $gatewayName ?>-<?= $methodName ?>">
                <label>
                    <input type="radio" name="payment_method" value="<?= $gatewayName . '.' . $methodName ?>">
                    <span class="gateway-label"><?= __(fnGet($gateway, 'label')) ?></span>
                    <span class="separator">-</span>
                    <span class="method-label"><?= __(fnGet($method, 'label')) ?></span>
                </label>
            </div>
        <?php } ?>
    <?php } ?>
    <div>
        <button type="submit"><?= __('Place Order') ?></button>
    </div>
    <div class="hidden">
        <input type="hidden" name="_token" value="<?= Session::getCsrfToken(true); ?>" autocomplete="off">
    </div>
</form>
