<?php
/* @var Phwoolcon\View\Engine\Php $this */
?>
<footer>
    <div class="footer">
        <div class="row">
            <div class="container">
                <div class="col c8">
                    <a>&copy; 2016 Phwoolcon</a>
                    <a href="<?= url('about-us'); ?>"><?= __('About Us'); ?></a>
                    <a href="<?= url('terms'); ?>"><?= __('Terms of Service'); ?></a>
                </div>
                <?php $this->include('page/locale-selector'); ?>
            </div>
        </div>
    </div>
</footer>
