<?php
/* @var Phwoolcon\View\Engine\Php $this */
?>
<footer>
    <div class="footer">
        <div class="container">
            <div class="col c8">
                <a href="<?php echo url('about-us'); ?>"><?php echo __('About Us'); ?></a>
                <a href="<?php echo url('terms'); ?>"><?php echo __('Terms of Service'); ?></a>
            </div>
            <?php $this->include('page/locale-selector'); ?>
        </div>
    </div>
</footer>
