<?php
/* @var Phwoolcon\View\Engine\Php $this */
?>
<header>
    <nav class="nav" tabindex="-1" onclick="this.focus()">
        <div class="container">
            <a href="<?php echo url(''); ?>" class="page-name"><?php echo __('Home'); ?></a>
            <?php if (Auth::getUser()) { ?>
                <a href="<?php echo url('account'); ?>"><?php echo __('My Account'); ?></a>
                <a href="<?php echo url('account/logout'); ?>"><?php echo __('Logout'); ?></a>
            <?php } else { ?>
                <a href="<?php echo url('account/login'); ?>"><?php echo __('Login'); ?></a>
                <a href="<?php echo url('account/register'); ?>"><?php echo __('Register'); ?></a>
            <?php } ?>
        </div>
    </nav>
</header>
