<?php
/* @var Phwoolcon\View\Engine\Php $this */
?>
<?php
if (View::noHeader()) {
    return;
}
?>
<header>
    <nav class="nav" tabindex="-1">
        <div class="container">
            <a href="<?= url(''); ?>" class="page-name"><?= __('Home'); ?></a>
            <?php if (Auth::getUser()) { ?>
                <a href="<?= url('account'); ?>"><?= __('My Account'); ?></a>
                <a href="<?= url('account/logout'); ?>"><?= __('Logout'); ?></a>
            <?php } else { ?>
                <a href="<?= url('account/login'); ?>"><?= __('Login'); ?></a>
                <a href="<?= url('account/register'); ?>"><?= __('Register'); ?></a>
            <?php } ?>
        </div>
    </nav>
</header>
