<?php
/* @var Phwoolcon\View\Engine\Php $this */
?>
<?php if ($locales = I18n::getAvailableLocales()) {
    $currentLocale = I18n::getCurrentLocale();
    $currentUrl = url($this->request->getURI());
?>
    <div class="locale-selector">
        <label>
            <span>Language:</span>
            <select id="locale-selector" class="js-only">
                <?php foreach ($locales as $k => $label) { ?>
                    <option value="<?php echo $k ?>" <?php if ($k == $currentLocale) { ?>selected="selected"<?php } ?>>
                        <?php echo $label; ?>
                    </option>
                <?php } ?>
            </select>
            <noscript>
                <ul>
                    <?php foreach ($locales as $k => $label) { ?>
                        <li>
                            <?php if ($k != $currentLocale) { ?><a href="<?php echo url('account/redirect', [
                                'redirect_url' => $currentUrl,
                                '_locale' => $k,
                                '_immediately' => true,
                            ]); ?>"><?php } ?>
                            <?php echo $label; ?>
                            <?php if ($k != $currentLocale) { ?></a><?php } ?>
                        </li>
                    <?php } ?>
                </ul>
            </noscript>
        </label>
    </div>
<?php } ?>
