<?php
/* @var Phwoolcon\View\Engine\Php $this */
?>
<?php if ($locales = I18n::getAvailableLocales()) {
    $currentLocale = I18n::getCurrentLocale();
    $currentUrl = url($this->request->getURI());
?>
    <div class="locale-selector col c4">
        <form action="<?= url('account/redirect'); ?>" method="get" target="_self">
            <label>
                <span>Language:</span>
                <select id="locale-selector" name="_locale">
                    <?php foreach ($locales as $k => $label) { ?>
                        <option value="<?= $k ?>" <?php if ($k == $currentLocale) { ?>selected="selected"<?php } ?>>
                            <?= $label; ?>
                        </option>
                    <?php } ?>
                </select>
                <noscript>
                    <button type="submit" class="submit btn btn-c smooth btn-sm"><span>&#10003;</span></button>
                </noscript>
            </label>
            <div class="hidden">
                <input type="hidden" name="_immediately" value="1">
                <input type="hidden" name="redirect_url" value="<?= $currentUrl; ?>">
            </div>
        </form>
    </div>
<?php } ?>
