<?php
/* @var Phalcon\Mvc\View\Engine\Php $this */
?>
<!DOCTYPE html>
<html lang="<?php echo View::getPageLanguage(); ?>" class="no-js">
<head>
    <meta charset="utf-8"/>
    <!-- JavaScript Detection -->
    <script type="text/javascript">(function (h) {h.className = h.className.replace('no-js', '')})(document.documentElement);</script>
    <!-- Mobile viewport optimisation -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="<?php echo View::getPageKeywords(); ?>">
    <meta name="description" content="<?php echo View::getPageDescription(); ?>">
    <title><?php echo View::getPageTitle(); ?></title>
    <?php View::generateHeadCss(); ?>
    <?php View::generateHeadJs(); ?>
    <?php View::generateIeHack(); ?>
</head>
<body>
<?php echo $this->getContent(); ?>
<?php View::generateBodyJs(); ?>
</body>
</html>
